# Generated by Django 4.1.13 on 2024-11-15 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nhanvien',
            options={},
        ),
    ]
