# Generated by Django 4.1.13 on 2024-11-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bangluong',
            name='maluong',
            field=models.AutoField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='baotri',
            name='mabt',
            field=models.AutoField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='calam',
            name='macalam',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dungcu',
            name='madc',
            field=models.AutoField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nghiphep',
            name='manp',
            field=models.AutoField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='thietbi',
            name='matb',
            field=models.AutoField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='thongtinnguyenlieu',
            name='manl',
            field=models.AutoField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
