# Generated by Django 4.1.13 on 2024-11-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_nhanvien_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhanvien',
            name='gioitinh',
            field=models.BooleanField(choices=[(True, 'Nam'), (False, 'Nữ')], default=True),
        ),
    ]
